@extends('layouts.template')

@section('title', 'Warehouse Grid')

@section('head')
    <link rel="stylesheet" href="{{ asset('css/grid.css') }}?v={{ time() }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="warehouse-id" content="{{ $warehouse->id }}">

    <style>
        /* page content */
        .content {
            flex: 1;
            width: 100%;
            padding: 0px 0px !important;
        }
    </style>
@endsection

@section('content')

    <div class="grid-container">
        <!-- Left Sidebar -->
        <div class="sidebar">
            <div class="sidebar-header">
                <h2 id="warehouseNameDisplay" class="editable-warehouse-name" title="Click to edit">
                    {{ $warehouse->warehouse_name }}</h2>
                <input type="text" id="warehouseNameInput" class="warehouse-name-input" style="display: none;"
                    value="{{ $warehouse->warehouse_name }}">
                <div class="header-buttons">
                    <a href="{{ route('dashboard') }}" class="btn-back">← Back</a>
                    <button type="button" class="btn-share" data-bs-toggle="modal" data-bs-target="#shareWarehouseModal">
                        Share
                    </button>
                </div>
            </div>

            <!-- Search Bar -->
            <div class="search-container">
                <input type="text" id="searchInput" class="search-input" placeholder="Search products...">
                <button id="clearSearchBtn" class="btn-clear-search">×</button>
            </div>

            <!-- Create Section Button -->
            <button type="button" class="btn-create-section" id="createSectionBtn">
                + Create Section
            </button>

            <!-- Sections List -->
            <div class="sections-list" id="sectionsList">
                @foreach ($warehouse->sections as $section)
                    <div class="section-item" data-section-id="{{ $section->id }}" data-grid-x="{{ $section->grid_x }}"
                        data-grid-y="{{ $section->grid_y }}">
                        <div class="section-item-header">
                            <span class="section-item-name editable-section-name" data-section-id="{{ $section->id }}"
                                title="Click to edit">{{ $section->section_name }}</span>
                            <div class="section-item-actions">
                                <button class="btn-add-product" data-section-id="{{ $section->id }}">+</button>
                                <button class="btn-delete-section" data-section-id="{{ $section->id }}">×</button>
                            </div>
                        </div>
                        <div class="section-item-products">
                            @foreach ($section->products as $product)
                                <div class="product-item-small" data-product-id="{{ $product->id }}"
                                    data-section-id="{{ $section->id }}">
                                    <span class="product-item-name">{{ $product->product_name }}</span>
                                    <span class="product-item-qty">Qty: {{ $product->quantity }}</span>
                                    <button class="btn-edit-product" data-section-id="{{ $section->id }}"
                                        data-product-id="{{ $product->id }}">✎</button>
                                    <button class="btn-delete-product" data-section-id="{{ $section->id }}"
                                        data-product-id="{{ $product->id }}">×</button>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
        </div>

        <!-- Main Grid Area -->
        <div class="grid-area">
            <div class="grid-canvas" id="gridCanvas">
                <!-- Grid cells will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- Modal for Creating Section -->
    <div class="modal fade" id="createSectionModal" tabindex="-1" aria-labelledby="createSectionModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createSectionModalLabel">Create New Section</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" id="sectionNameInput" placeholder="Enter section name">
                    <p class="modal-hint">Click on an empty grid cell to place the section</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Adding Product -->
    <div class="modal fade" id="createProductModal" tabindex="-1" aria-labelledby="createProductModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createProductModalLabel">Add Product to <span id="modalSectionName"></span>
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="productSectionId">
                    <div class="mb-3">
                        <label for="productName" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="productName" placeholder="Enter product name">
                    </div>
                    <div class="mb-3">
                        <label for="productSku" class="form-label">SKU (Optional)</label>
                        <input type="text" class="form-control" id="productSku" placeholder="Enter SKU">
                    </div>
                    <div class="mb-3">
                        <label for="productQuantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="productQuantity" placeholder="Enter quantity"
                            value="0" min="0">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="addProductBtn">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Editing Product -->
    <div class="modal fade" id="editProductModal" tabindex="-1" aria-labelledby="editProductModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editProductModalLabel">Edit Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="editProductId">
                    <input type="hidden" id="editProductSectionId">
                    <div class="mb-3">
                        <label for="editProductName" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="editProductName"
                            placeholder="Enter product name">
                    </div>
                    <div class="mb-3">
                        <label for="editProductSku" class="form-label">SKU (Optional)</label>
                        <input type="text" class="form-control" id="editProductSku" placeholder="Enter SKU">
                    </div>
                    <div class="mb-3">
                        <label for="editProductQuantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="editProductQuantity" placeholder="Enter quantity"
                            value="0" min="0">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="updateProductBtn">Update Product</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Sharing Warehouse -->
    <div class="modal fade" id="shareWarehouseModal" tabindex="-1" aria-labelledby="shareWarehouseModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="shareWarehouseModalLabel">Share Warehouse</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="shareEmail" class="form-label">User Email</label>
                        <input type="email" class="form-control" id="shareEmail" placeholder="Enter user email">
                    </div>
                    <button type="button" class="btn btn-primary mb-3" id="shareWarehouseBtn">Add User</button>

                    <hr class="my-4">

                    <h6 class="shared-users-title">Users with Access</h6>
                    <div id="sharedUsersList" class="shared-users-list">
                        <!-- Shared users will be loaded here -->
                        <p class="loading-users">Loading...</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script src="{{ asset('js/grid.js') }}?v={{ time() }}"></script>
@endsection
